app/_components/LoginButton.tsx
로그인 버튼 hover 색상 수정 및 link href 연결
어떤 변경 사항이 있나요?
=> :sparkles: feat: update hover color and link href

app/signin/page.tsx
=> :sparkles: feat: Connect Backend Server

app/_components/KakaoLoginButton.tsx, app/kakao-signup/_components/KakaoSignUpForm.tsx, app/kakao-signup/page.tsx
=> :sparkles: feat: Add kakao signup

app/_components/MenuBar.tsx, app/kakao-signup/_components/KakaoSignUpForm.tsx, app/kakao-signup/page.tsx, app/user-info/page.tsx, public/icons/icon-add-diary.svg, public/icons/icon-calendar.svg, public/icons/icon-diary.svg, public/icons/icon-home.svg, public/icons/icon-mypage.svg
=> :sparkles: feat: Add Menu Bar

app/user-info/_components/ProfileTitleForm.tsx, app/user-info/page.tsx
=> :sparkles: feat: Add logout and delete account

app/edit-page/_components/TitleForm.tsx, app/edit-page/page.tsx, app/kakao-signup/_components/KakaoSignUpForm.tsx, app/kakao-signup/page.tsx, app/signup/_components/SignUpForm.tsx, app/user-info/_components/ProfileTitleForm.tsx
=> :bug: fix: delete unused import

app/edit-page/_components/TitleForm.tsx
=> :bug: fix: fix className spelling error

app/edit-page/_components/TitleForm.tsx, app/edit-page/page.tsx
=> :bug: fix: fix props passing error

app/kakao-signup/_components/KakaoSignUpForm.tsx
=> :bug: fix: fix kakaosignupform spelling error

app/kakao-signup/_components/KakaoSignUpForm.tsx, app/kakao-signup/page.tsx
=> :bug: fix: fix delete cookie

app/user-info/_components/InfoForm.tsx
=> :bug: fix: fix InfoForm passing prop type

app/user-info/_components/ProfileTitleForm.tsx
=> :bug: fix: fix ProfileTitleForm passing prop type

app/contents/page.tsx, app/proxy/route.ts, app/user-info/_components/InfoForm.tsx, app/user-info/page.tsx
=> :sparkles: feat: get user-info from back

app/diary-detail/page.tsx, app/diary/page.tsx
=> :sparkles: add diary delete

app/_components/BackButton.tsx, app/_components/KakaoLoginButton.tsx, app/_components/MenuBar.tsx, app/content-detail/page.tsx, app/dashboard/_components/ReturnToLoginPage.tsx, app/dashboard/page.tsx, app/diary-detail/page.tsx, app/diary/page.tsx, app/kakao-signup/_components/KakaoSignUpForm.tsx, app/kakao-signup/page.tsx, app/signin/_components/SignInForm.tsx, app/signin/page.tsx, app/signup/page.tsx, app/user-info/_components/InfoForm.tsx, app/user-info/_components/ProfileTitleForm.tsx, app/write-diary/_component/writeForm.tsx, app/write-diary/page.tsx
=> ✨ add write-diary

app/diary-detail/page.tsx, app/diary/_components/DiaryList.tsx
=> :sparkles: add unauthorized

app/_components/ErrorPage.tsx, app/diary-detail/page.tsx, app/user-info/_components/InfoForm.tsx, app/user-info/_components/UserInfoForm.tsx, app/user-info/page.tsx, app/write-diary/_component/WriteForm.tsx, public/icons/icon-error.svg
=> :sparkles: add unauthorized error

app/user-info/_components/ProfileTitleForm.tsx, app/write-diary/_component/WriteForm.tsx
=> :sparkles: add logout and delete account

app/dashboard/_components/TodaySportCard.tsx, app/dashboard/_sections/TodaySportSection.tsx, next.config.ts
=> :sparkles: add today contents in dashboard

app/user-info/_components/ProfileTitleForm.tsx
=> :sparkles: feat: add ai analysis
